import math
angle1=int(input())
radius1=int(input())
angle2=int(input())
radius2=int(input())
sector_paq=(angle1/360)*radius1*radius1*(22/7)
print(sector_paq)
sector_pbq=(angle2/360)*radius2*radius2*(22/7)
print(sector_pbq)
triangle_paq=(1/2)*radius1*radius1*math.sin(math.radians(angle1))
print(triangle_paq)
triangle_pbq=(1/2)*radius2*radius2*math.sin(math.radians(angle2))
print(triangle_pbq)
result=(sector_paq-triangle_paq)+(sector_pbq-triangle_pbq)
print(math.ceil(result))
